"""
Django settings for projeto project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import inspect

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-64&#!%_zd%)0w#96@y0x53ac@19h-=op)@8s*qle0ki9xgr!2m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'tarefas',
    'rest_framework.authtoken',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'projeto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'projeto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
 'DEFAULT_AUTHENTICATION_CLASSES': [
 'rest_framework.authentication.TokenAuthentication',
 'rest_framework.authentication.SessionAuthentication', # para login via web
 ],
 'DEFAULT_PERMISSION_CLASSES': [
 'rest_framework.permissions.IsAuthenticatedOrReadOnly', # GET liberado, outros métodos exigem login
 ],
 'DEFAULT_FILTER_BACKENDS': [
 'django_filters.rest_framework.DjangoFilterBackend',
 ],
 'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'API de Projetos e Tarefas',
    'DESCRIPTION': inspect.cleandoc("""
    ## Bem-vindo à API de Gestão de Projetos e Tarefas!

    Esta API permite gerenciar Projetos e suas respectivas Tarefas.

    ### 📌 Endpoints Principais

    #### **Projetos**
    - `GET /api/projetos/` — Listar projetos
    - `POST /api/projetos/` — Criar projeto
    - `GET /api/projetos/{id}/` — Detalhar projeto
    - `PUT/PATCH /api/projetos/{id}/` — Atualizar projeto
    - `DELETE /api/projetos/{id}/` — Excluir projeto

    #### **Tarefas**
    - `GET /api/tarefas/` — Listar tarefas
    - `GET /api/tarefas/?projeto=<id>` — Filtrar tarefas por projeto
    - `POST /api/tarefas/` — Criar tarefa
    - `GET /api/tarefas/{id}/` — Detalhar tarefa
    - `PUT/PATCH /api/tarefas/{id}/` — Atualizar tarefa
    - `DELETE /api/tarefas/{id}/` — Excluir tarefa

    ### 🔐 Autenticação
    Gere seu token usando o endpoint:

    ```
    POST /api/token/
    ```

    Envie no cabeçalho:

    ```
    Authorization: Token <seu_token>
    ```

    """),

    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,

    # Segurança padrão com token
    'SECURITY': [{'TokenAuth': []}],

    'COMPONENTS': {
        'securitySchemes': {
            'TokenAuth': {
                'type': 'apiKey',
                'in': 'header',
                'name': 'Authorization',
                'description': 'Use o formato: Token <seu_token>',
            },
        },
    },
}
